// Put in Typescript types here
export const TYPES = {
  Bot: Symbol("Bot"),
  Client: Symbol("Client"),
  DiscordToken: Symbol("Token"),
  MessageResponder: Symbol("MessageResponder"),
  PingFinder: Symbol("PingFinder"),
  LeetcodeProblemParser: Symbol("LeetcodeProblemParser"),
  LeetcodeProblem: Symbol("LeetcodeProblem"),
  LeetcodeDifficulty: Symbol("LeetcodeDifficulty"),
  LeetcodeProblemDownloader: Symbol("LeetcodeProblemDownloader"),
  LeetcodeFileLoader: Symbol("LeetcodeFileLoader"),
  LeetcodeProblemSelector: Symbol("LeetcodeProblemSelector"),
  LeetcodeEmbedCreator: Symbol("LeetcodeEmbedCreator"),
  RedditUsername: Symbol("RedditUsername"),
  RedditPassword: Symbol("RedditPassword"),
  RedditClientID: Symbol("RedditClientID"),
  RedditClientSecret: Symbol("RedditClientSecret"),
  RedditOAuthGenerator: Symbol("RedditOAuthGenerator"),
  RedditFetchTop: Symbol("RedditFetchTop"),
  RedditRandomPostGenerator: Symbol("RedditRandomPostGenerator"),
  RedditPostParser: Symbol("RedditPostParser"),
  RedditEmbedCreator: Symbol("RedditEmbedCreator"),
  AskRedditFetcher: Symbol("AskRedditFetcher"),
};
